Organizations:
  - &Org1
    Name: Org1
    MSPID: Org1MSP
    Domain: org1.fnodocker.icu
    Nodes:
      - Name: peer0
        ListenPort: 7051
        ChaincodeListenPort: 7052
        OperationsListenPort: 9443
      - Name: peer1
        ListenPort: 8051
        ChaincodeListenPort: 8052
        OperationsListenPort: 10443
      - &orderer0
        Name: orderer0
      - &orderer1
        Name: orderer1
  - &Org2
    Name: Org2
    MSPID: Org2MSP
    Domain: org2.fnodocker.icu
    Nodes:
      - Name: peera
        ListenPort: 9051
        ChaincodeListenPort: 9052
        OperationsListenPort: 11443
      - Name: peerb
        ListenPort: 10051
        ChaincodeListenPort: 10052
        OperationsListenPort: 12443
      - &orderera
        Name: orderera
      - &ordererb
        Name: ordererb

SystemChannel:
  Name: sys-channel-nodocker
  Organizations:
    - *Org1
    - *Org2
  Orderers:
    - *orderer0
    - *orderer1
    - *orderera
    - *ordererb

UserChannels:
  Name: mychannel